
DROP TABLE IF EXISTS schedule_job;
DROP TABLE IF EXISTS schedule_job_log;
DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_LOCKS;
DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;

DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_CALENDARS;
DROP TABLE IF EXISTS QRTZ_TRIGGERS;
DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
-- 定时任务

CREATE TABLE `schedule_job` (
  `job_id` bigint(20) NOT NULL COMMENT '任务id',
  `bean_name` varchar(200) DEFAULT NULL COMMENT 'spring bean名称',
  `params` varchar(2000) DEFAULT NULL COMMENT '参数',
  `cron_expression` varchar(100) DEFAULT NULL COMMENT 'cron表达式',
  `status` tinyint(4) DEFAULT NULL COMMENT '任务状态  0：正常  1：暂停',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='定时任务';

-- 定时任务日志

CREATE TABLE `schedule_job_log` (
  `log_id` bigint(20) NOT NULL COMMENT '任务日志id',
  `job_id` bigint(20) NOT NULL COMMENT '任务id',
  `bean_name` varchar(200) DEFAULT NULL COMMENT 'spring bean名称',
  `params` varchar(2000) DEFAULT NULL COMMENT '参数',
  `status` tinyint(4) NOT NULL COMMENT '任务状态    0：成功    1：失败',
  `error` varchar(2000) DEFAULT NULL COMMENT '失败信息',
  `times` int(11) NOT NULL COMMENT '耗时(单位：毫秒)',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  PRIMARY KEY (`log_id`),
  KEY `job_id` (`job_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='定时任务日志';






--  quartz自带表结构

CREATE TABLE QRTZ_JOB_DETAILS(
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '调度器名称',
  JOB_NAME VARCHAR(200) NOT NULL COMMENT '任务名称',
  JOB_GROUP VARCHAR(200) NOT NULL COMMENT '任务群组',
  DESCRIPTION VARCHAR(250) NULL COMMENT '调度器说明',
  JOB_CLASS_NAME VARCHAR(250) NOT NULL COMMENT '任务class全路径',
  IS_DURABLE VARCHAR(1) NOT NULL COMMENT '是否持久性任务',
  IS_NONCONCURRENT VARCHAR(1) NOT NULL COMMENT '是否并行',
  IS_UPDATE_DATA VARCHAR(1) NOT NULL COMMENT '是否更新日期',
  REQUESTS_RECOVERY VARCHAR(1) NOT NULL COMMENT '是否唤醒',
  JOB_DATA BLOB NULL COMMENT '任务数据',
  PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='定时任务明细';

CREATE TABLE QRTZ_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器群组',
  JOB_NAME VARCHAR(200) NOT NULL COMMENT '作业名称',
  JOB_GROUP VARCHAR(200) NOT NULL COMMENT '作业群组',
  DESCRIPTION VARCHAR(250) NULL COMMENT '说明信息',
  NEXT_FIRE_TIME BIGINT(13) NULL COMMENT '下次执行时间',
  PREV_FIRE_TIME BIGINT(13) NULL COMMENT '上次执行时间',
  PRIORITY INTEGER NULL COMMENT '线程优先级',
  TRIGGER_STATE VARCHAR(16) NOT NULL COMMENT '触发状态',
  TRIGGER_TYPE VARCHAR(8) NOT NULL COMMENT '触发器类型',
  START_TIME BIGINT(13) NOT NULL COMMENT '开始时间',
  END_TIME BIGINT(13) NULL COMMENT '结束时间',
  CALENDAR_NAME VARCHAR(200) NULL COMMENT '日历名称',
  MISFIRE_INSTR SMALLINT(2) NULL COMMENT '失败警告',
  JOB_DATA BLOB NULL COMMENT '任务数据',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
  REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='触发器和作业绑定';

CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器组',
  REPEAT_COUNT BIGINT(7) NOT NULL COMMENT '重复次数',
  REPEAT_INTERVAL BIGINT(12) NOT NULL COMMENT '重复间隔',
  TIMES_TRIGGERED BIGINT(10) NOT NULL COMMENT '触发次数',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='任务计划';


CREATE TABLE QRTZ_CRON_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器群组',
  CRON_EXPRESSION VARCHAR(120) NOT NULL COMMENT 'cron表达式',
  TIME_ZONE_ID VARCHAR(80)  COMMENT '时区',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='cron触发器';


CREATE TABLE QRTZ_SIMPROP_TRIGGERS
(
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器组',
  STR_PROP_1 VARCHAR(512) NULL COMMENT 'String类型的trigger的第一个参数',
  STR_PROP_2 VARCHAR(512) NULL COMMENT 'String类型的trigger的第二个参数',
  STR_PROP_3 VARCHAR(512) NULL COMMENT 'String类型的trigger的第三个参数',
  INT_PROP_1 INT NULL COMMENT 'int类型的trigger的第一个参数',
  INT_PROP_2 INT NULL COMMENT 'int类型的trigger的第二个参数',
  LONG_PROP_1 BIGINT NULL COMMENT 'long类型的trigger的第一个参数',
  LONG_PROP_2 BIGINT NULL COMMENT 'long类型的trigger的第二个参数',
  DEC_PROP_1 NUMERIC(13,4) NULL COMMENT 'decimal类型的trigger的第一个参数',
  DEC_PROP_2 NUMERIC(13,4) NULL COMMENT 'decimal类型的trigger的第二个参数',
  BOOL_PROP_1 VARCHAR(1) NULL COMMENT 'Boolean类型的trigger的第一个参数',
  BOOL_PROP_2 VARCHAR(1) NULL COMMENT 'Boolean类型的trigger的第二个参数',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = '用来存储存储CalendarIntervalTrigger和DailyTimeIntervalTrigger';


CREATE TABLE QRTZ_BLOB_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器群组',
  BLOB_DATA BLOB NULL COMMENT '基本信息',
  PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
  INDEX (SCHED_NAME,TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
  REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自定义触发器';


CREATE TABLE QRTZ_CALENDARS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  CALENDAR_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  CALENDAR BLOB NOT NULL COMMENT '日历信息',
  PRIMARY KEY (SCHED_NAME,CALENDAR_NAME))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='日历信息触发器';

CREATE TABLE QRTZ_PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器组',
  PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='被暂停的触发器';


CREATE TABLE QRTZ_FIRED_TRIGGERS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  ENTRY_ID VARCHAR(95) NOT NULL COMMENT '组织id',
  TRIGGER_NAME VARCHAR(200) NOT NULL COMMENT '触发器名称',
  TRIGGER_GROUP VARCHAR(200) NOT NULL COMMENT '触发器组',
  INSTANCE_NAME VARCHAR(200) NOT NULL COMMENT '实例名称',
  FIRED_TIME BIGINT(13) NOT NULL COMMENT '触发时间',
  SCHED_TIME BIGINT(13) NOT NULL COMMENT '计划时间',
  PRIORITY INTEGER NOT NULL COMMENT '权重',
  STATE VARCHAR(16) NOT NULL COMMENT '状态',
  JOB_NAME VARCHAR(200) NULL COMMENT '作业名称',
  JOB_GROUP VARCHAR(200) NULL COMMENT '作业群组',
  IS_NONCONCURRENT VARCHAR(1) NULL COMMENT '是否并行',
  REQUESTS_RECOVERY VARCHAR(1) NULL COMMENT '是否要求唤醒',
  PRIMARY KEY (SCHED_NAME,ENTRY_ID))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='空闲的触发器';


CREATE TABLE QRTZ_SCHEDULER_STATE (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '调度器名称',
  INSTANCE_NAME VARCHAR(200) NOT NULL COMMENT '实例化时间',
  LAST_CHECKIN_TIME BIGINT(13) NOT NULL COMMENT '最后验证时间',
  CHECKIN_INTERVAL BIGINT(13) NOT NULL COMMENT '时间间隔',
  PRIMARY KEY (SCHED_NAME,INSTANCE_NAME))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='调度器状态';


CREATE TABLE QRTZ_LOCKS (
  SCHED_NAME VARCHAR(120) NOT NULL COMMENT '计划名称',
  LOCK_NAME VARCHAR(40) NOT NULL COMMENT '锁名称',
  PRIMARY KEY (SCHED_NAME,LOCK_NAME))
  ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='通过悲观锁获取触发器';




CREATE INDEX IDX_QRTZ_J_REQ_RECOVERY ON QRTZ_JOB_DETAILS(SCHED_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_J_GRP ON QRTZ_JOB_DETAILS(SCHED_NAME,JOB_GROUP);

CREATE INDEX IDX_QRTZ_T_J ON QRTZ_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_JG ON QRTZ_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_T_C ON QRTZ_TRIGGERS(SCHED_NAME,CALENDAR_NAME);
CREATE INDEX IDX_QRTZ_T_G ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_N_G_STATE ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_GROUP,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(SCHED_NAME,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_STATE,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_STATE);
CREATE INDEX IDX_QRTZ_T_NFT_ST_MISFIRE_GRP ON QRTZ_TRIGGERS(SCHED_NAME,MISFIRE_INSTR,NEXT_FIRE_TIME,TRIGGER_GROUP,TRIGGER_STATE);

CREATE INDEX IDX_QRTZ_FT_TRIG_INST_NAME ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME);
CREATE INDEX IDX_QRTZ_FT_INST_JOB_REQ_RCVRY ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,INSTANCE_NAME,REQUESTS_RECOVERY);
CREATE INDEX IDX_QRTZ_FT_J_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_JG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,JOB_GROUP);
CREATE INDEX IDX_QRTZ_FT_T_G ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP);
CREATE INDEX IDX_QRTZ_FT_TG ON QRTZ_FIRED_TRIGGERS(SCHED_NAME,TRIGGER_GROUP);

