server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;
    # resolver {NAME_SERVER}  valid=10s;
    # resolver_timeout 3s;
    client_max_body_size     20m;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }


    location ~ /(api|oauth|oauth2|business) {
        proxy_buffers 16 10m;
        proxy_buffer_size 20m;
        proxy_busy_buffers_size 20m;
        proxy_pass http://100.115.103.232:9008;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
